PROVINCIA_PREFIX = {
    "ÁLAVA": "01",
    "ALBACETE": "02",
    "ALICANTE": "03",
    "ALMERÍA": "04",
    "ÁVILA": "05",
    "BADAJOZ": "06",
    "ILLES BALEARS": "07",
    "BALEARES": "07",
    "BARCELONA": "08",
    "BURGOS": "09",
    "CÁCERES": "10",
    "CÁDIZ": "11",
    "CASTELLÓN": "12",
    "CIUDAD REAL": "13",
    "CÓRDOBA": "14",
    "A CORUÑA": "15",
    "CUENCA": "16",
    "GIRONA": "17",
    "GRANADA": "18",
    "GUADALAJARA": "19",
    "GIPUZKOA": "20",
    "HUELVA": "21",
    "HUESCA": "22",
    "JAÉN": "23",
    "LEÓN": "24",
    "LLEIDA": "25",
    "LA RIOJA": "26",
    "LUGO": "27",
    "MADRID": "28",
    "MÁLAGA": "29",
    "MURCIA": "30",
    "NAVARRA": "31",
    "OURENSE": "32",         # "ORENSE" en castellano
    "ASTURIAS": "33",
    "PALENCIA": "34",
    "LAS PALMAS": "35",
    "PONTEVEDRA": "36",
    "SALAMANCA": "37",
    "SANTA CRUZ DE TENERIFE": "38",
    "STA. CRUZ DE TENERIFE":"38",
    "CANTABRIA": "39",
    "SEGOVIA": "40",
    "SEVILLA": "41",
    "SORIA": "42",
    "TARRAGONA": "43",
    "TERUEL": "44",
    "TOLEDO": "45",
    "VALENCIA": "46",
    "VALLADOLID": "47",
    "BIZKAIA": "48",         # "VIZCAYA" en castellano
    "ZAMORA": "49",
    "ZARAGOZA": "50",
    "CEUTA": "51",
    "MELILLA": "52"
}